Partie 1 – Series
1) Créer une Series contenant 4 températures

In [3]:
import pandas as pd
temperature = pd.Series([34.5, 23.4, 19.8, 34.2])
temperature

0    34.5
1    23.4
2    19.8
3    34.2
dtype: float64

2) afficher son index

In [4]:
print(temperature.index)

RangeIndex(start=0, stop=4, step=1)

3) Afficher la 1ère valeur

In [5]:
print(temperature[0])

34.5

4) Afficher la dernière valeur

In [8]:
print(temperature[3])

34.2

5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de
mesure 12h, 13h, 14h et 15h

In [ ]:
#premiere facon
temperature = pd.Series([34.5, 23.4, 19.8, 34.2], 
index=["12h", "13h", "14h", "15h"])

print(temperature)

12h    34.5
13h    23.4
14h    19.8
15h    34.2
dtype: float64

In [18]:
#deuxieme facon
temperature = pd.Series({
  "12h" : "34.5",
  "13h" : "23.4",
  "14h" : "19.8",
  "15h" : "34.2",
 })

print(temperature)

12h    34.5
13h    23.4
14h    19.8
15h    34.2
dtype: object

6) Afficher la 1ère et la dernière valeur

In [23]:
print(temperature.loc["12h"])
print(temperature.loc["15h"])

34.5
34.2

Partie 2 – DataFrame
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant
data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}

In [25]:
df_test = pd.DataFrame(
    data = {
        "capteur": ["C001", "C002", "C003"],
        "temperature": [24.5, 25.1, 26.3],
        "humidite": [65, 67, 70]
        }
)

print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2) Importer le dataset mesures_capteurs.csv dans le dataframe df

In [41]:
df = pd.read_csv("../data/mesures_capteurs.csv")

3) Afficher les dimensions de df

In [42]:
df.ndim

2

Partie 3 – Exploration
1) Afficher les premières lignes

In [43]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2) Afficher les 10 premières lignes

In [44]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3) Afficher les dernieres lignes

In [45]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4) afficher le nombre de lignes

In [50]:
print(df.shape[0])

605

5) Afficher le nombre de colonnes

In [51]:
print(df.shape[1])

9

6) Afficher les noms des colonnes

In [52]:
print(df.columns)

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

7) Afficher les informations générales

In [56]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB
None

8) afficher les statistiques descriptives

In [55]:
print(df.describe())

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection
1) Sélectionner la colonne "temperature"

In [57]:
print(df["temperature"])

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [59]:
print(df[["temperature", "humidite", "pression", "consommation"]])

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

3) Sélectionner les 5 premières lignes avec loc

In [61]:
print(df.loc[:4])

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80

   pression  consommation etat
0   1008.95        287.28   OK
1    993.39        116.20   OK
2   1010.32        288.50   OK
3   1019.62        136.65   OK
4   1016.58        182.62   OK

4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [62]:
print(df.iloc[:4, :3])

  id_mesure           date_heure id_capteur
0     M0413  2026-01-22 04:00:00       C005
1     M0290  2026-01-17 01:00:00       C002
2     M0077  2026-01-08 04:00:00       C005
3     M0079  2026-01-08 06:00:00       C007

Partie 5 – Manipulation des colonnes
1) Ajouter la colonne "temperature_fahrenheit"

In [104]:
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32

In [105]:
print(df.columns)
print(df["temperature_fahrenheit"])

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat',
       'temperature_fahrenheit'],
      dtype='object')
0      77.828
1      75.200
2      78.476
3      82.814
4      69.044
        ...
600    74.606
601    75.812
602    74.714
603    76.694
604    62.636
Name: temperature_fahrenheit, Length: 605, dtype: float64

2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en
"Élevée" (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [75]:
import numpy as np
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Elevée", "Normal")

In [76]:
print(df.columns)

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat',
       'temperature_fahrenheit', 'niveau_temperature'],
      dtype='object')

3) Renommer la colonne "humidite" en "humidite_relative"

In [96]:
df.rename(columns={"humidite": "humidite_relative"}, inplace=True)

In [98]:
print(df.columns)

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat'],
      dtype='object')

4) Supprimer la colonne "temperature_fahrenheit"

In [108]:
df.drop("temperature_fahrenheit", axis=1, inplace=True)

In [109]:
print(df.columns)

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat'],
      dtype='object')

Partie 6 – Filtrage
1) Récupérer uniquement les lignes telles que température > 30

In [113]:
df[df["temperature"] > 30]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK
103,M0311,2026-01-17 22:00:00,C011,B004,30.83,54.99,1026.47,256.11,OK
112,M0149,2026-01-11 04:00:00,C005,B002,31.46,48.48,1002.75,210.94,OK
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE
137,M0076,2026-01-08 03:00:00,C004,B002,31.18,49.66,1019.91,215.22,OK
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE
174,M0405,2026-01-21 20:00:00,C009,B003,31.74,47.23,1015.59,115.79,OK
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK
243,M0416,2026-01-22 07:00:00,C008,B003,30.16,54.00,1012.18,875.00,ERREUR
246,M0312,2026-01-17 23:00:00,C012,B004,30.13,65.68,1009.70,198.65,OK
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE
257,M0378,2026-01-20 17:00:00,C006,B002,31.99,66.32,1013.54,254.67,OK
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK
274,M0046,2026-01-06 21:00:00,C010,B004,30.92,67.19,1009.71,329.78,OK
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK
322,M0120,2026-01-09 23:00:00,C012,B004,30.19,53.58,1013.05,396.90,ALERTE
356,M0574,2026-01-28 21:00:00,C010,B004,30.61,60.73,1022.32,321.75,OK
362,M0396,2026-01-21 11:00:00,C012,B004,30.57,63.47,1017.40,248.36,OK
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE
401,M0586,2026-01-29 09:00:00,C010,B004,31.44,63.10,996.56,271.51,OK
404,M0598,2026-01-29 21:00:00,C010,B004,30.37,64.55,997.31,311.77,OK
417,M0432,2026-01-22 23:00:00,C012,B004,30.38,65.98,1005.48,256.18,OK
437,M0286,2026-01-16 21:00:00,C010,B004,32.16,41.80,996.99,255.56,ALERTE
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK
488,M0431,2026-01-22 22:00:00,C011,B004,30.14,51.02,1007.70,366.53,ALERTE
492,M0552,2026-01-27 23:00:00,C012,B004,30.24,62.06,1009.35,299.69,OK
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR
505,M0268,2026-01-16 03:00:00,C004,B002,30.34,64.23,1011.42,179.84,OK
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK
558,M0346,2026-01-19 09:00:00,C010,B004,30.68,36.33,1010.46,272.59,OK

2) Récupérer uniquement les lignes telles température > 30 et humidité > 70

In [121]:
print(df.columns)

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite_relative', 'pression', 'consommation', 'etat'],
      dtype='object')

In [ ]:
df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK

Partie 7 : Tri
1) Créer df_trie1 pour trier en fonction de la température croissante

In [125]:
df_trie1 = df.sort_values("temperature", ascending=True)
print(df_trie1)

    id_mesure           date_heure id_capteur batiment  temperature  \
487     M0538  2026-01-27 09:00:00       C010     B004       -18.50
245     M0127  2026-01-10 06:00:00       C007     B003        14.11
258     M0223  2026-01-14 06:00:00       C007     B003        15.49
249     M0175  2026-01-12 06:00:00       C007     B003        16.04
59      M0146  2026-01-11 01:00:00       C002     B001        16.77
..        ...                  ...        ...      ...          ...
163     M0019  2026-01-05 18:00:00       C007     B003          NaN
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN
548     M0572  2026-01-28 19:00:00       C008     B003          NaN
556     M0092  2026-01-08 19:00:00       C008     B003          NaN

     humidite_relative  pression  consommation    etat
487              66.27   1012.49        312.92  ERREUR
245             145.00   1032.36        169.57  ERREUR
258              47.96   1006.34        124.90      OK
249              55.36   1005.68        140.95      OK
59               53.44   1010.65        131.75      OK
..                 ...       ...           ...     ...
163              69.97   1014.14        181.07      OK
215              59.96   1007.98        294.02      OK
513              52.97   1010.71        253.63      OK
548              68.63   1018.58        252.48      OK
556              79.81   1007.05        113.00      OK

[605 rows x 9 columns]

2) Créer df_trie2 pour trier en fonction de la température décroissante

In [129]:
df_trie2 = df.sort_values(["temperature"], ascending=False)
print(df_trie2)

    id_mesure           date_heure id_capteur batiment  temperature  \
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
..        ...                  ...        ...      ...          ...
163     M0019  2026-01-05 18:00:00       C007     B003          NaN
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN
548     M0572  2026-01-28 19:00:00       C008     B003          NaN
556     M0092  2026-01-08 19:00:00       C008     B003          NaN

     humidite_relative  pression  consommation    etat
502              81.51   1026.79        271.92  ERREUR
43               57.50   1008.94        266.22  ALERTE
129              79.80   1021.96        212.55  ALERTE
211              50.43   1009.87        356.76  ALERTE
165              73.24   1014.36        260.24  ALERTE
..                 ...       ...           ...     ...
163              69.97   1014.14        181.07      OK
215              59.96   1007.98        294.02      OK
513              52.97   1010.71        253.63      OK
548              68.63   1018.58        252.48      OK
556              79.81   1007.05        113.00      OK

[605 rows x 9 columns]

3) Créer top10 pour voir les 10 températures les plus élevées3) Créer top10 pour voir les 10 températures les plus élevées

In [130]:
top10 = df.sort_values(["temperature"], ascending=False).head(10)

4) Trier en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

In [132]:
trier = df.sort_values(
    ["batiment", "temperature"],
    ascending=[True, False]
)

print(trier)

    id_mesure           date_heure id_capteur batiment  temperature  \
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
447     M0170  2026-01-12 01:00:00       C002     B001        31.15
224     M0303  2026-01-17 14:00:00       C003     B001        30.84
500     M0062  2026-01-07 13:00:00       C002     B001        30.39
9       M0087  2026-01-08 14:00:00       C003     B001        28.85
..        ...                  ...        ...      ...          ...
277     M0383  2026-01-20 22:00:00       C011     B004        20.60
338     M0060  2026-01-07 11:00:00       C012     B004        20.56
487     M0538  2026-01-27 09:00:00       C010     B004       -18.50
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN

     humidite_relative  pression  consommation    etat
520              53.28   1010.05        195.37  ALERTE
447              69.20   1016.10        172.49      OK
224              67.98   1020.09        157.99      OK
500              52.13   1004.23        262.66      OK
9                44.37   1008.27        206.59      OK
..                 ...       ...           ...     ...
277              71.17   1017.44        293.92      OK
338              63.37   1004.50        256.18      OK
487              66.27   1012.49        312.92  ERREUR
215              59.96   1007.98        294.02      OK
513              52.97   1010.71        253.63      OK

[605 rows x 9 columns]

Partie 8 : Analyse
1) Afficher la consommation moyenne par bâtiment

In [138]:
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

In [ ]:
2) Afficher le minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment

In [145]:
df.groupby("batiment")["temperature"].agg(["min", "max", "std"])

            min    max       std
batiment
B001      16.77  32.72  2.961211
B002      17.67  33.60  2.951828
B003      14.11  31.74  2.983902
B004     -18.50  58.70  5.367361

3) Afficher, par bâtiment, le maximum et la moyenne de la température et de la consommation

In [148]:
df.groupby("batiment")[["temperature","consommation"]].agg(["max","mean"])

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

4) Afficher la température moyenne globale

In [151]:
df["temperature"].mean()

np.float64(24.87831385642738)

5) Afficher la température maximale

In [153]:
df["temperature"].max()

np.float64(58.7)

6) Afficher la consommation totale

In [154]:
df["consommation"].sum()

np.float64(125205.25)

7) Quel bâtiment consomme le plus en moyenne ?

In [158]:
df.groupby("batiment")["consommation"].mean().idxmax()

'B004'

8) Afficher le nombre d'alertes par bâtiment

In [160]:
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

Partie 9 : Gestion des valeurs manquantes
1) Afficher le nombre de valeurs manquantes par colonne

In [162]:
print(df.isna().sum())

id_mesure            0
date_heure           0
id_capteur           0
batiment             0
temperature          6
humidite_relative    5
pression             5
consommation         5
etat                 4
dtype: int64

2) Afficher le nombre total des valeurs manquantes

In [163]:
df.isna().sum().sum()

np.int64(25)

3) Afficher le taux de valeurs manquantes

In [164]:
df.isna().mean() * 100

id_mesure            0.000000
date_heure           0.000000
id_capteur           0.000000
batiment             0.000000
temperature          0.991736
humidite_relative    0.826446
pression             0.826446
consommation         0.826446
etat                 0.661157
dtype: float64

5) Pour la température et l’humidité, remplacer les valeurs manquantes par les moyennes

In [166]:
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"] = df["humidite_relative"].fillna(df["humidite_relative"].mean())