Partie 1 – Series
1) Créer une Series contenant 4 températures

In [3]:
import pandas as pd
temperature = pd.Series([34.5, 23.4, 19.8, 34.2])
temperature

0    34.5
1    23.4
2    19.8
3    34.2
dtype: float64

2) afficher son index

In [4]:
print(temperature.index)

RangeIndex(start=0, stop=4, step=1)

3) Afficher la 1ère valeur

In [5]:
print(temperature[0])

34.5

4) Afficher la dernière valeur

In [8]:
print(temperature[3])

34.2

5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de
mesure 12h, 13h, 14h et 15h

In [ ]:
#premiere facon
temperature = pd.Series([34.5, 23.4, 19.8, 34.2], 
index=["12h", "13h", "14h", "15h"])

print(temperature)

12h    34.5
13h    23.4
14h    19.8
15h    34.2
dtype: float64

In [18]:
#deuxieme facon
temperature = pd.Series({
  "12h" : "34.5",
  "13h" : "23.4",
  "14h" : "19.8",
  "15h" : "34.2",
 })

print(temperature)

12h    34.5
13h    23.4
14h    19.8
15h    34.2
dtype: object

6) Afficher la 1ère et la dernière valeur

In [23]:
print(temperature.loc["12h"])
print(temperature.loc["15h"])

34.5
34.2

Partie 2 – DataFrame
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant
data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}

In [25]:
df_test = pd.DataFrame(
    data = {
        "capteur": ["C001", "C002", "C003"],
        "temperature": [24.5, 25.1, 26.3],
        "humidite": [65, 67, 70]
        }
)

print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2) Importer le dataset mesures_capteurs.csv dans le dataframe df

In [41]:
df = pd.read_csv("../data/mesures_capteurs.csv")

3) Afficher les dimensions de df

In [42]:
df.ndim

2

Partie 3 – Exploration
1) Afficher les premières lignes

In [43]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2) Afficher les 10 premières lignes

In [44]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3) Afficher les dernieres lignes

In [45]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4) afficher le nombre de lignes

In [50]:
print(df.shape[0])

605

5) Afficher le nombre de colonnes

In [51]:
print(df.shape[1])

9